:encoding: utf-8
:lang: ja
:author: 笹川 尋翔
:email: nagutabby@nagutabby.uk

:scripts: cjk
:pdf-theme: default-with-fallback-font
:last-update-label!:

:toc: left
:toclevels: 3
:toc-title: 目次

:example-caption: 例
:table-caption: 表
:figure-caption: 図

:source-highlighter: highlight.js

= 2023年度PD3

== リポジトリ
* https://github.com/nagutabby/senior-thesis[リサーチプロポーザルと卒論]
* https://github.com/nagutabby/pd3-note[PD3のメモ]

== Wiki
* 読んだ論文
** https://github.com/nagutabby/senior-thesis/wiki/Bringing-the-Web-up-to-Speed-with-WebAssembly[Bringing the Web up to Speed with WebAssembly]
** https://github.com/nagutabby/senior-thesis/wiki/Everything-Old-is-New-Again:-Binary-Security-of-WebAssembly[Everything Old is New Again: Binary Security of WebAssembly]
** https://github.com/nagutabby/senior-thesis/wiki/Forming-a-5G-Strategy-for-Developing-Countries:-A-Note-for-Policy-Makers[Forming a 5G Strategy for Developing Countries: A Note for Policy Makers]
** https://github.com/nagutabby/senior-thesis/wiki/Impact-of-Progressive-Web-Apps-on-Web-App-Development[Impact of Progressive Web Apps on Web App Development]
** https://github.com/nagutabby/senior-thesis/wiki/Not-So-Fast:-Analyzing-the-Performance-of-WebAssembly-vs.-Native-Code[Not So Fast: Analyzing the Performance of WebAssembly vs. Native Code]
** https://github.com/nagutabby/senior-thesis/wiki/OpenCV.js:-computer-vision-processing-for-the-open-web-platform[OpenCV.js: computer vision processing for the open web platform]
** https://github.com/nagutabby/senior-thesis/wiki/Progressive-Web-Apps-for-the-Unified-Development-of-Mobile-Applications[Progressive Web Apps for the Unified Development of Mobile Applications]
** https://github.com/nagutabby/senior-thesis/wiki/Progressive-Web-Apps:-the-Definite-Approach-to-Cross%E2%80%90Platform-Development%3F[Progressive Web Apps: the Definite Approach to Cross‐Platform Development?]
* https://github.com/nagutabby/senior-thesis/wiki/Chrome,-Edge,-Safari,-Firefox%E3%81%AE%E7%89%B9%E5%BE%B4[Chrome, Edge, Safari, Firefoxの特徴]
* https://github.com/nagutabby/senior-thesis/wiki/Facts-and-Figures-2022[Facts and Figures 2022]
* https://github.com/nagutabby/senior-thesis/wiki/Lighthouse%E3%81%AE%E3%83%A1%E3%83%88%E3%83%AA%E3%82%AF%E3%82%B9[Lighthouseのメトリクス]
* https://github.com/nagutabby/senior-thesis/wiki/Web-API[Web API]
* https://github.com/nagutabby/senior-thesis/wiki/%E3%83%A2%E3%83%90%E3%82%A4%E3%83%AB%E9%80%9A%E4%BF%A1%E3%81%AE%E4%B8%96%E4%BB%A3%E3%81%A8%E7%8F%BE%E7%8A%B6[モバイル通信の世代と現状]
* https://github.com/nagutabby/senior-thesis/wiki/%E6%83%85%E5%A0%B1%E9%80%9A%E4%BF%A1%E7%99%BD%E6%9B%B8%E4%BB%A4%E5%92%8C5%E5%B9%B4%E7%89%88[情報通信白書令和5年版]
* https://github.com/nagutabby/senior-thesis/wiki/%E7%8F%BE%E5%9C%A8%E5%88%A9%E7%94%A8%E5%8F%AF%E8%83%BD%E3%81%AA%E5%9B%BD%E5%86%85%E3%81%AE%E8%A6%B3%E5%85%89%E6%A1%88%E5%86%85%E3%82%A2%E3%83%97%E3%83%AA%E3%81%AE%E4%B8%80%E8%A6%A7[現在利用可能な国内の観光案内アプリの一覧]

== 2023/4/6
指導していただいた時間: 3.5時間 +
活動した時間: 3.5時間 +
内容: ゼミのオリエンテーションを行った

== 2023/4/7
活動した時間: 6.0時間 +
内容: 公式ドキュメントの手順に従ってns-3の環境構築を行った

== 2023/4/9
活動した時間: 3.0時間 +
内容: 公式ドキュメントの手順に従ってUbuntu上でns-3の環境構築を行った

== 2023/4/10
活動した時間: 3.0時間 +
内容: 公式ドキュメントの手順に従ってMacOS X上でns-3の環境構築を行った

== 2023/4/17
指導していただいた時間: 3.5時間 +
活動した時間: 5.5時間 +
内容: 端末の時刻を同期するための仕組みを調べた

== 2023/4/19
活動した時間: 3.0時間 +
内容: 研究で利用できそうなネットワークシミュレーターを調べた

== 2023/4/24
指導していただいた時間: 3.5時間 +
活動した時間: 5.5時間 +
内容: Webアプリのアクセシビリティーの水準を高めるための仕様であるWAI-ARIAを調べた

== 2023/4/26
活動した時間: 5.0時間 +
内容: Webアプリのアクセシビリティーを高める方法を学習した

== 2023/4/30
活動した時間: 3.0時間 +
内容: モバイル通信システムの概要と特徴を調べた

== 2023/5/1
指導していただいた時間: 3.5時間 +
活動した時間: 5.5時間 +
内容: 研究室のメンバーから研究の計画を聞き、質疑応答を行った

== 2023/5/2
活動した時間: 2.0時間 +
内容: 関連研究の論文(Towards Smart Farming and Sustainable Agriculture with Drones)を読んだ

== 2023/5/5
活動した時間: 2.0時間 +
内容: 研究の概要を説明するスライドを作成した

== 2023/5/8
指導していただいた時間: 3.5時間 +
活動した時間: 3.5時間 +
内容: 研究室のメンバーから研究の計画を聞き、質疑応答を行った

== 2023/5/9
活動した時間: 3.0時間 +
内容: 関連研究の論文(Collection of Data with Drones in Precision Agriculture: Analytical Model and LoRa Case Study)を読んだ

== 2023/5/14
活動した時間: 4.0時間 +
内容: 関連研究の論文(Smart Farming: Opportunities, Challenges and Technology Enablers)を読んだ

== 2023/5/15
活動した時間: 2.0時間 +
内容: 次世代のモバイル通信システムを利用したUAVの自律制御に関する小論文を書いた

== 2023/5/23
活動した時間: 4.0時間 +
内容: 関連研究の論文(The Digitisation of Agriculture: a Survey of Research Activities on Smart Farming)を読んだ

== 2023/5/24
活動した時間: 3.0時間 +
内容: 関連研究の論文(A Review on UAV-Based Applications for Precision Agriculture)を読んだ

== 2023/5/25
活動した時間: 3.0時間 +
内容: 関連研究の論文(Smart farming for improving agricultural management)を読んだ

== 2023/5/29
指導していただいた時間: 4.0時間 +
活動した時間: 4.0時間 +
内容: 研究室のメンバーから研究の計画を聞き、質疑応答を行った

== 2023/5/30
活動した時間: 2.0時間 +
内容: 関連研究の論文(D2D-Assisted Multi-User Cooperative Partial Offloading in MEC Based on Deep Reinforcement Learning)を読んだ

== 2023/5/31
活動した時間: 3.0時間 +
内容: 関連研究の論文(An Integrated Precision Farming Application Based on 5G, UAV and Deep Learning Technologies)を読んだ

== 2023/6/4
活動した時間: 2.0時間 +
内容: 次世代のモバイル通信システムを利用したUAVの自律制御に関する小論文を書いた

== 2023/6/5
活動した時間: 4.0時間 +
内容: 関連研究の論文(Data acquisition and analysis methods in UAV-based applications for Precision Agriculture)を読んだ

== 2023/6/6
活動した時間: 1.5時間 +
内容: 関連研究の論文(A Low-Cost Platform for Environmental Smart Farming Monitoring System Based on IoT and UAVs)を読んだ

== 2023/6/8
活動した時間: 1.5時間 +
内容: 関連研究の論文(Future of Smart Farming with Internet of Things)を読んだ

== 2023/6/9
活動した時間: 2.0時間 +
内容: 研究の概要を説明するスライドを作成した

== 2023/6/11
活動した時間: 3.5時間 +
内容: 関連研究の論文(Influence of Drone Altitude, Image Overlap, and Optical Sensor Resolution on Multi-View Reconstruction of Forest Images)を読んだ

== 2023/6/12
指導していただいた時間: 4.0時間 +
活動した時間: 4.0時間 +
内容: 研究室のメンバーから研究の計画を聞き、質疑応答を行った

== 2023/6/13
活動した時間: 2.0時間 +
内容: 研究の概要を説明するスライドを作成した

== 2023/6/20
活動した時間: 2.0時間 +
内容: 研究のプレゼンの練習をした

== 2023/6/22
活動した時間: 3.0時間 +
内容: 関連研究の論文(Modern Lossless Compression Techniques: Review, Comparison and Analysis)を読んだ

== 2023/6/23
活動した時間: 1.5時間 +
内容: 研究の概要を説明するスライドを作成した

== 2023/6/26
指導していただいた時間: 3.5時間 +
活動した時間: 3.5時間 +
内容: 中間発表で使用する予稿の書き方を覚えた

== 2023/6/27
活動した時間: 5.0時間 +
内容: 研究で扱う可能性がある概念である行列を理解するために線形代数の勉強をした

== 2023/6/28
活動した時間: 4.0時間 +
内容: 英語の論文を読む効率を上げるために英語の勉強をした

== 2023/6/29
活動した時間: 6.0時間 +
内容: 研究で扱う可能性がある概念である行列を理解するために線形代数の勉強をした

== 2023/7/2
活動した時間: 6.0時間 +
内容: 英語の論文を読む効率を上げるために英語の勉強をした

== 2023/7/3
指導していただいた時間: 3.0時間 +
活動した時間: 4.0時間 +
内容: 中間発表で使用する予稿の下書きを作成した

== 2023/7/4
活動した時間: 2.0時間 +
内容: 研究で扱う可能性がある概念である行列を理解するために線形代数の勉強をした

== 2023/7/14
活動した時間: 3.0時間 +
内容: 関連研究の論文(Everything Old is New Again: Binary Security of WebAssembly)を読んだ

== 2023/7/15
活動した時間: 2.5時間 +
内容: 関連研究の論文(Bringing the Web up to Speed with WebAssembly)を読んだ

== 2023/7/18
活動した時間: 2.0時間 +
内容: 関連研究の論文(OpenCV.js: computer vision processing for the open web platform)を読んだ

== 2023/7/19
活動した時間: 2.0時間 +
内容: 関連研究の論文(Not So Fast: Analyzing the Performance of WebAssembly vs. Native Code)を読んだ

== 2023/7/21
活動した時間: 4.0時間 +
内容: 関連研究の論文(Progressive Web Apps: the Definite Approach to Cross‐Platform Development?)を読んだ

== 2023/7/23
活動した時間: 3.0時間 +
内容: 関連研究の論文(Progressive Web Apps for the Unified Development of Mobile Applications)を読んだ

== 2023/7/24
活動した時間: 3.0時間 +
内容: 関連研究の論文(Impact of Progressive Web Apps on Web App Development)を読んだ

== 2023/7/26
活動した時間: 4.0時間 +
内容: 中間発表で使用するスライドを作成した

== 2023/7/27
指導していただいた時間: 3.5時間 +
活動した時間: 4.5時間 +
内容: 中間発表で使用するスライドを作成した

== 2023/7/30
活動した時間: 2.5時間 +
内容: 研究で使用しているWebアプリケーションサーバーの開発環境を整備した

== 2023/7/31
指導していただいた時間: 3.5時間 +
活動した時間: 3.5時間 +
内容: 中間発表で使用するスライドを作成した

== 2023/8/2
活動した時間: 1.5時間 +
内容: 研究で使用しているWebアプリケーションサーバーの開発環境を整備した

== 2023/8/6
活動した時間: 3.0時間 +
内容: MDNを利用してPWAの仕様を学んだ

== 2023/8/7
活動した時間: 4.0時間 +
内容: Webブラウザー側で使用されるWeb APIを調べ、リスト形式でまとめた

== 2023/8/10
活動した時間: 4.0時間 +
内容: What PWA Can Do Todayを利用してPWAで使用される有名なWeb APIを学んだ

== 2023/8/19
活動した時間: 2.0時間 +
内容: 中間発表で使用するスライドの視認性を改善した

== 2023/8/20
活動した時間: 3.5時間 +
内容: Webブラウザー側で使用されるWeb APIを調べ、リスト形式でまとめた

== 2023/8/21
指導していただいた時間: 4.0時間 +
活動した時間: 4.0時間 +
内容: 中間発表で使用する資料を作成する際の注意点を覚えた

== 2023/8/24
活動した時間: 3.0時間 +
内容: Web APIのWebブラウザー側の対応状況を調べ、リスト形式でまとめた

== 2023/8/28
指導していただいた時間: 4.5時間 +
活動した時間: 5.5時間 +
内容: 中間発表に向けてプレゼンの練習をした

== 2023/8/31
活動した時間: 4.0時間 +
内容: 中間発表で使用するポスターを作成した

== 2023/9/1
指導していただいた時間: 4.5時間 +
活動した時間: 5.0時間 +
内容: 中間発表に向けてプレゼンの練習をした

== 2023/9/6
活動した時間: 4.0時間 +
内容: 主要なWebブラウザーの特徴を調べ、リスト形式でまとめた

== 2023/9/7
活動した時間: 4.0時間 +
内容: Lighthouseのメトリクスの意味と算出方法を調べた

== 2023/9/10
活動した時間: 2.0時間 +
内容: 中間発表用の予稿のレビューをした

== 2023/9/11
指導していただいた時間: 3.5時間 +
活動した時間: 5.0時間 +
内容: 中間発表用の予稿のレビューをした

== 2023/9/17
活動した時間: 3.5時間 +
内容: モバイル通信システムの仕様と国内での歴史を調べた

== 2023/9/19
活動した時間: 4.0時間 +
内容: 情報通信白書令和5年版を読んだ

== 2023/9/24
活動した時間: 2.5時間 +
内容: 検証用のWebアプリの開発環境を構築した

== 2023/9/25
活動した時間: 3.0時間 +
内容: Overpass APIの使い方を覚えた

== 2023/9/26
指導していただいた時間: 3.5時間 +
活動した時間: 4.5時間 +
内容: 研究の進捗報告と研究の進め方に関する議論を行った

== 2023/9/27
活動した時間: 5.0時間 +
内容: Leafletの使い方を学び、検証用のWebアプリに実装した

== 2023/10/1
活動した時間: 3.0時間 +
内容: 都道府県別に観光名所を検索できるようにした

== 2023/10/2
活動した時間: 2.0時間 +
内容: 検証用のWebアプリの視認性を改善した

== 2023/10/3
指導していただいた時間: 3.0時間 +
活動した時間: 4.0時間 +
内容: 研究の進捗報告と研究の進め方に関する議論を行った

== 2023/10/6
活動した時間: 2.0時間 +
内容: Facts and Figures 2022を読んだ

== 2023/10/9
活動した時間: 2.5時間 +
内容: Facts and Figures 2022を読んだ

== 2023/10/12
活動した時間: 3.5時間 +
内容: 国内の観光案内アプリが利用している権限や、そのアプリに実装されている機能を調べた

== 2023/10/14
活動した時間: 3.0時間 +
内容: 国内の観光案内アプリが利用している権限や、そのアプリに実装されている機能を調べた

== 2023/10/16
活動した時間: 4.0時間 +
内容: Lighthouseをプログラム内で使用する方法を調べた

== 2023/10/17
指導していただいた時間: 3.5時間
活動した時間: 5.0時間
内容: 研究の進捗報告と研究の進め方に関する議論を行った

== 2023/10/18
活動した時間: 2.0時間 +
内容: ネットワークスロットリングの種類やネットワークスロットリングツールを調べた

== 2023/10/20
活動した時間: 1.0時間 +
内容: ネットワークスロットリングツールを試した

== 2023/10/21
活動した時間: 2.5時間 +
内容: 検証用のWebアプリのパフォーマンスを計測するプログラムを作成した

== 2023/10/22
活動した時間: 2.0時間 +
内容: 検証用のWebアプリのパフォーマンスを計測するプログラムを作成した

== 2023/10/24
活動した時間: 2.0時間 +
内容: Web APIのリストを整理した

== 2023/10/26
活動した時間: 3.0時間 +
内容: 国内の観光案内アプリが利用している権限や、そのアプリに実装されている機能を調べた

== 2023/10/28
活動した時間: 3.5時間 +
内容: 国内の観光案内アプリが利用している権限や、そのアプリに実装されている機能を図表にまとめた

== 2023/10/31
指導していただいた時間: 3.5時間 +
活動した時間: 4.0時間 +
内容: 研究の進捗報告と研究の進め方に関する議論を行った

== 2023/11/3
活動した時間: 3.0時間 +
内容: 検証用のWebアプリをデプロイした

== 2023/11/4
活動した時間: 3.5時間 +
内容: WebブラウザーによるキャッシュとCache APIによるキャッシュの違いを調べた

== 2023/11/07
活動した時間: 2.5時間 +
内容: Node modules版のLighthouse端末のエミュレーションを行う方法を調べた

== 2023/11/08
活動した時間: 2.0時間 +
内容: 検証用のWebアプリのパフォーマンスを計測するプログラムを作成した

== 2023/11/09
活動した時間: 3.5時間 +
内容: これまでのPD3の活動で得た情報をドキュメントにまとめた

== 2023/11/12
活動した時間: 4.0時間 +
内容: 検証用のWebアプリのパフォーマンスを計測した

== 2023/11/14
指導していただいた時間: 4.0時間
活動した時間: 5.0時間 +
内容: 卒論の書き方を覚えた

== 2023/11/15
活動した時間: 3.0時間 +
内容: 検証用のWebアプリのパフォーマンスを計測した

== 2023/11/16
活動した時間: 2.0時間 +
内容: Node modules版のLighthouseにおいてWebブラウザーによるキャッシュを無効にする方法を調べた

== 2023/11/18
活動した時間: 1.0時間 +
内容: 検証用のWebアプリのパフォーマンスを計測するプログラムを修正した

== 2023/11/20
活動した時間: 5.0時間 +
内容: 検証用のWebアプリのパフォーマンスを計測した

== 2023/11/21
指導していただいた時間: 4.0時間 +
活動した時間: 5.0時間 +
内容: 研究の進捗報告と研究の進め方に関する議論を行った

== 2023/11/23
活動した時間: 4.0時間 +
内容: 検証用のWebアプリのパフォーマンスを計測した

== 2023/11/24
活動した時間: 2.0時間 +
内容: Elasticsearch, Kibanaをインストールした

== 2023/11/26
活動した時間: 2.0時間 +
内容: Elasticsearch, Kibanaを使用してメトリクスのデータを分析した

== 2023/11/27
活動した時間: 4.0時間 +
内容: 卒論の「背景」項目を書いた

== 2023/11/28
指導していただいた時間: 4.0時間 +
活動した時間: 4.5時間 +
内容: 研究の進捗報告と研究の進め方に関する議論を行った

== 2023/11/29
活動した時間: 3.0時間 +
内容: 卒論の「関連研究」項目を書いた

== 2023/11/30
活動した時間: 4.0時間 +
内容: 卒論の「研究内容」項目を書いた

== 2023/12/1
活動した時間: 5.0時間 +
内容: 卒論の「研究内容」項目を書いた

== 2023/12/3
活動した時間: 5.0時間 +
内容: 卒論の「研究内容」項目を書いた

== 2023/12/4
活動した時間: 4.0時間 +
内容: 卒論の「評価」項目を書いた

== 2023/12/5
指導していただいた時間: 4.0時間 +
活動した時間: 4.0時間 +
内容: 研究の進捗報告と研究の進め方に関する議論を行った

== 2023/12/6
活動した時間: 3.0時間 +
内容: 卒論の「考察」項目を書いた

== 2023/12/7
活動した時間 2.0時間 +
内容: 卒論の「評価」項目の一部を「関連研究」項目に移した

== 2023/12/11
活動した時間: 2.0時間 +
内容: 卒論の下書きのセルフレビューをした

== 2023/12/12
指導していただいた時間: 4.0時間 +
活動した時間: 4.0時間 +
内容: 研究の進捗報告と研究の進め方に関する議論を行った

== 2023/12/15
活動した時間: 2.0時間 +
内容: 卒論の下書きのセルフレビューをした

== 2023/12/18 +
活動した時間: 2.5時間 +
内容: 卒論のレビューを基に文章を修正した

== 2023/12/19
指導していただいた時間: 3.5時間 +
活動した時間: 3.5時間 +
内容: 卒論の下書きのレビューをした

== 2023/12/20
活動した時間: 2.0時間 +
内容: 卒論の「結論」項目を書いた

== 2023/12/21
活動した時間: 3.0時間 +
内容: 「Usability of Mobile Applications: A Systematic Literature Study」を読み、モバイルアプリのユーザビリティーに影響する要素を学んだ

== 2023/12/22
活動した時間: 2.0時間 +
内容: Webアプリの自動テストを行うライブラリを調べた

== 2023/12/23
活動した時間: 1.5時間 +
内容: Chrome Devtools ProtocolとWebDriverの違いを調べた

== 2023/12/24
活動した時間: 3.0時間 +
内容: スクロールやズーム操作を行った際のリソースの処理時間を、PuppeteerとResource Timing APIを使用して計測した

== 2023/12/25
活動した時間: 4.0時間 +
内容: スクロールやズーム操作を行った際のリソースの処理時間を、PuppeteerとResource Timing APIを使用して計測した

== 2023/12/26
活動した時間:2.0時間 +
内容: スクロールやズーム操作を行った際のリソースの処理時間をElasticsearchとKibanaを使用して分析した

== 2023/12/28
活動した時間: 2.0時間 +
内容: ユーザーの操作に基づいたパフォーマンス分析の方法を、卒論の「研究内容」項目に追記した

== 2024/1/2
活動した時間: 2.0時間 +
内容: ユーザーの操作に基づいたパフォーマンス分析の結果を、卒論の「評価」項目に追記した

== 2024/1/4
活動した時間: 1.5時間 +
内容: ユーザーの操作に基づいたパフォーマンス分析の結果を、卒論の「まとめ」項目に追記した

== 2024/1/7
活動した時間: 2.0時間 +
内容: 卒論の予稿を1ページ書いた

== 2024/1/9
活動した時間: 2.0時間 +
内容: 卒論の予稿を1ページ書いた

== 2024/1/10
活動した時間: 3.0時間 +
内容: PD3の予稿をレビューした

== 2024/1/11
活動した時間: 1.5時間 +
内容: PD3の予稿をレビューした

== 2024/1/13
活動した時間: 1.0時間 +
内容: 卒論の予稿を修正した

== 2024/1/15
活動した時間: 2.5時間 +
内容: 卒論と卒論の予稿を印刷した

== 2024/1/16
指導していただいた時間: 2.5時間 +
活動した時間: 4.5時間 +
内容: 卒論と卒論の予稿を提出した

== 2024/1/24
活動した時間: 2.0時間 +
内容: 卒論の図を修正した

== 2024/1/25
指導していただいた時間: 4.0時間 +
活動した時間: 4.0時間 +
内容: 卒論の発表用のスライドをレビューした

== 2024/1/30
指導していただいた時間: 4.0時間 +
活動した時間: 4.0時間 +
内容: 卒論の発表用のスライドをレビューした

== 2024/1/31
活動した時間: 3.0時間 +
内容: 卒論の文章を分かりやすくした
